[project]
name = "vapt-agent-tester"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-generativeai>=0.8.5",
    "langgraph>=0.5.3",
    "nicegui>=2.21.1",
    "python-dotenv>=1.1.1",
]
